---
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    hocon: https://github.com/puppetlabs/puppetlabs-hocon.git
