---
.pdkignore:
  paths:
    - /.*.yml
    - /pdk.yaml
    - /.pmtignore
    - /.git*
    - /.editorconfig
    - /provision.yaml
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
